### ISSUE TITLE
Error installing in windows 10

### ISSUE THREAD

**Issue by felicemarra** [astronautlabs/libyuv-node#5]
when I try to install I get this error 

`  Generazione del codice in corso...
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_std_error non risolto nella funzione "public: __
cdecl libyuv::MJpegDecoder::MJpegDecoder(void)" (??0MJpegDecoder@libyuv@@QEAA@XZ) [D:\Sviluppo\VirtualTVStudio\mixer\no
de_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_CreateDecompress non risolto nella funzione "pub
lic: __cdecl libyuv::MJpegDecoder::MJpegDecoder(void)" (??0MJpegDecoder@libyuv@@QEAA@XZ) [D:\Sviluppo\VirtualTVStudio\m
ixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_destroy_decompress non risolto nella funzione "p
ublic: __cdecl libyuv::MJpegDecoder::~MJpegDecoder(void)" (??1MJpegDecoder@libyuv@@QEAA@XZ) [D:\Sviluppo\VirtualTVStudi
o\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_read_header non risolto nella funzione "public:
int __cdecl libyuv::MJpegDecoder::LoadFrame(unsigned char const *,unsigned __int64)" (?LoadFrame@MJpegDecoder@libyuv@@Q
EAAHPEBE_K@Z) [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_start_decompress non risolto nella funzione "pri
vate: int __cdecl libyuv::MJpegDecoder::StartDecode(void)" (?StartDecode@MJpegDecoder@libyuv@@AEAAHXZ) [D:\Sviluppo\Vir
tualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_read_raw_data non risolto nella funzione "public
: int __cdecl libyuv::MJpegDecoder::DecodeToBuffers(unsigned char * *,int,int)" (?DecodeToBuffers@MJpegDecoder@libyuv@@
QEAAHPEAPEAEHH@Z) [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_abort_decompress non risolto nella funzione "pub
lic: int __cdecl libyuv::MJpegDecoder::DecodeToBuffers(unsigned char * *,int,int)" (?DecodeToBuffers@MJpegDecoder@libyu
v@@QEAAHPEAPEAEHH@Z) [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
mjpeg_decoder.obj : error LNK2019: riferimento al simbolo esterno jpeg_resync_to_restart non risolto nella funzione "pu
blic: __cdecl libyuv::MJpegDecoder::MJpegDecoder(void)" (??0MJpegDecoder@libyuv@@QEAA@XZ) [D:\Sviluppo\VirtualTVStudio\
mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\Release\libyuv.dll : fatal error LNK1120: 8 e
sterni non risolti [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\external\libyuv\out\yuv_shared.vcxproj]
  Building Custom Rule D:/Sviluppo/VirtualTVStudio/mixer/node_modules/libyuv/external/libyuv/CMakeLists.txt
  CMake does not need to re-run because D:/Sviluppo/VirtualTVStudio/mixer/node_modules/libyuv/external/libyuv/out/CMake
  Files/generate.stamp is up-to-date.`

then 

`d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\cpu_id.cc(1): fatal error C1083: Non è possibile aprire il fi
le inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcx
proj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\rotate.cc(11): fatal error C1083: Non è possibile aprire il f
ile inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vc
xproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\scale_argb.cc(1): fatal error C1083: Non è possibile aprire i
l file inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv
.vcxproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\scale.cc(1): fatal error C1083: Non è possibile aprire il fil
e inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcxp
roj]
  rotate_argb.cc
  win_delay_load_hook.cc
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\convert.h(11): fatal error C1083: Non è possibile aprire il f
ile inclusione: 'napi.h': No such file or directory (compilazione del file di origine ..\src\convert.cc) [D:\Sviluppo\V
irtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcxproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\convert_argb.h(11): fatal error C1083: Non è possibile aprire
 il file inclusione: 'napi.h': No such file or directory (compilazione del file di origine ..\src\init.cc) [D:\Sviluppo
\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcxproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\convert_argb.h(11): fatal error C1083: Non è possibile aprire
 il file inclusione: 'napi.h': No such file or directory (compilazione del file di origine ..\src\convert_argb.cc) [D:\
Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcxproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\version.h(1): fatal error C1083: Non è possibile aprire il fi
le inclusione: 'napi.h': No such file or directory (compilazione del file di origine ..\src\version.cc) [D:\Sviluppo\Vi
rtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcxproj]
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\rotate_argb.cc(11): fatal error C1083: Non è possibile aprire
 il file inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\y
uv.vcxproj]`

**Comment by rezonant** [comment]
Ahh yes, looks like it detected libjpeg on your system. We have the JPEG portions disabled on Linux and Mac (as the binding itself does not yet support the JPEG features of libyuv) but looks like I missed it on the Windows platform (I don't have a JPEG library available for it to use I guess).

Give `libyuv@0.0.3` a try, it now patches out the JPEG portions when building on Windows, should do the trick!

Let me know how it goes and thanks for using the library!

**Comment by rezonant** [comment]
```
d:\sviluppo\virtualtvstudio\mixer\node_modules\libyuv\src\cpu_id.cc(1): fatal error C1083: Non è possibile aprire il fi le inclusione: 'napi.h': No such file or directory [D:\Sviluppo\VirtualTVStudio\mixer\node_modules\libyuv\build\yuv.vcx proj]
```
This error indicates that the `node-addon-api` package was not installed (it is a dependency of `libyuv`)-
what version of Node.js are you using? CircleCI currently tests Node 12 on Windows, and on Linux we test 8, 10, 12, and 14. 
Note if you are using an odd-numbered version of Node.js you won't be able to use this library as from what I understand unstable Node.js versions do not include the Addon API.

**Comment by felicemarra** [comment]
with 
npm install node-addon-api

works. thanks
